version: "3"
networks:
  app-network:

services:
  app:
    container_name: app
    networks:
      - app-network
    environment:
      PORT: 9003
      DB_URL: "host=snuffleupagus.db.elephantsql.com user=kbtaxwhu password=VthO3y1OPdi4GXxVcW8PE11ddTAxC1W2 dbname=kbtaxwhu port=5432 sslmode=disable"
      RABBITMQ_URI: "amqp://user:password@rabbitmq:5672/"
      RABBITMQ_QUEUE: products
      REDIS_URL: redis:6379
    build: .
    ports:
      - "9003:9003"
    volumes:
      - type: bind
        source: ./tmp/feed
        target: /tmp/feed
    depends_on:
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:latest
    networks:
      - app-network
    environment:
      POSTGRES_DB: "kbtaxwhu"
      POSTGRES_USER: "kbtaxwhu"
      POSTGRES_PASSWORD: "VthO3y1OPdi4GXxVcW8PE11ddTAxC1W2"
      POSTGRES_HOST: "snuffleupagus.db.elephantsql.com"
      POSTGRES_PORT: 5432
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    networks:
      - app-network
    environment:
      REDIS_URL: "redis://redis:6379"
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:latest
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 25s
      retries: 10
      timeout: 5s
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
